### ISSUE TITLE
Farseek causing NoSuchMethod errors on methods that take IBakedModel

### ISSUE THREAD

**Issue by maxpowa** [delvr/Farseek#10]
Seems to be that Farseek is stripping out `isValid` from FFS's `PropertyModel` because it takes an `IBakedModel` as a parameter. 

Lordmau5/FFS#55

https://gist.github.com/anonymous/29d025e419f4f0127eb94db10fba3d8a

Seems to be stripping out something from ActuallyAdditions as well.

Edit: In FFS's case the mod works fine on a server without Farseek.

**Comment by delvr** [comment]
Thanks for reporting this. It will be fixed in the next update.

**Comment by JCMais** [comment]
if you have it fixed and have the time to do so, can you release a new version on forge please?

This is crashing FFS and Forestry.

**Comment by Lordmau5** [comment]
Any news on this?
I got 2 more issue reports on FFS in the last 3 days.

**Comment by adrwa** [comment]
Any news on this?
Alot of issues are coming up.

**Comment by delvr** [comment]
Yeah I feel your pain guys, I've also been closing duplicates of this one left and right. Things got real busy around here, but I expect a patch release tomorrow (Sunday) or Monday. Thanks for your patience.

**Comment by Lordmau5** [comment]
Sweet, thanks! :)

**Comment by delvr** [comment]
Fixed in v1.9.4-1.1.
