### ISSUE TITLE
Maybe it's an Odd Oodle

### ISSUE THREAD

**Issue by kreezxil** [delvr/Farseek#14]
One of my players is getting an odd crash report, I say odd, because I had Waila and removed it in favor WIT. But a mod apparently is looking for Waila, yours is the first one that I recognize in the stack trace, I'm reporting this to all the mods in there as I'm not sure who should get this report.

crash report: http://pastebin.com/Q6a8an9R

**Comment by kreezxil** [comment]
I submitted it to both your githubs, so close the one that doesn't apply, if neither apply, that's ok too. Just close with a comment as to where this report should really go, I reported to mcjty too.

**Comment by delvr** [comment]
Yeah the Farseek coremod doesn't play nice with @Optional interfaces like Waila provides. I'm trying to fix the codemod logic for the long-term and meanwhile have been hardcoding mod paths to exclude. Looks like I forgot one for ImmersiveCraft last time. Hopefully I can fix the whole logic soon or I'll be patching for every mod that uses Waila which isn't sustainable. Stay tuned for updates.

**Comment by delvr** [comment]
This should be fixed in Farseek 2.0. Please give it a try and let me know of any issues, thanks!

**Comment by kreezxil** [comment]
Are you in the military? or something that keeps you away for months on
end? I only ask because the bug report is really old.
