### ISSUE TITLE
Farseek Wants Forge 1.9 on 1.10.2

### ISSUE THREAD

**Issue by cjburkey01** [delvr/Farseek#17]
On the Curseforge download page, Farseek claims to be compatible with 1.10, but when launched in 1.10.2, it says it will only work with 1.9.  Does it work on plain 1.10, or is it an issue with your version in Forge?

**Comment by delvr** [comment]
Make sure you download the 1.9.4 version and not 1.9. Curseforge has 1.9 as the default since it's the last one I uploaded, not sure how to change that. Maybe I'll try re-uploading 1.9.4 as-is so it becomes the latest. Anyway please let me know if 1.9.4 works for you.

**Comment by delvr** [comment]
With the new 1.9.4-2.0 release, the default Farseek file should now be the latest.
