### ISSUE TITLE
[1.9.4 - 1.1] NoSuchMethodError - Water Strainer Mod

### ISSUE THREAD

**Issue by Ruuubi** [delvr/Farseek#19]
Hello. I think you are aware of this, but some mods don't play nice together with Farseek.
I think you fixed some issues with other mods, but mine (https://minecraft.curseforge.com/projects/water-strainer) keeps crashing while Farseek is on the server with a NoSuchMethodError.

Some crash logs:
- https://gist.github.com/kreezxil/ac4bb2ca7d0c76412bad7a21ff1c4fe2
- http://pastebin.com/sM6Tm2cf

**Comment by delvr** [comment]
This should be fixed in Farseek 2.0. Please give it a try and let me know of any issues, thanks!
