### ISSUE TITLE
[1.7.10] Creation of Structure Generation Chunk Provider causing server to time out

### ISSUE THREAD

**Issue by GunmetalGears** [delvr/Farseek#25]
Farseek 1.1 fixed the majority of the issues with the generation of a river causing problems, but it doesn't appear to have caused all of them. With Terrafirmacraft, sometimes when a river generates the world will simply stop loading; the game stops loading new content. Zero chunk updates, blocks do not drop, the game/server eventually time out and stop working.

I cannot provide a crash report as this isn't a crash; I'm almost entirely certain this is a problem with Farseek because the last thing in my game's log before timing out is the mod trying to create a structure generation chunk provider for TFC.

**Comment by delvr** [comment]
Thanks for reporting; this is the same issue as https://github.com/delvr/Farseek/issues/22 which will have a fix ready shortly.
