### ISSUE TITLE
cascading world gen 1.11.2

### ISSUE THREAD

**Issue by pabthelamb** [delvr/Farseek#28]
when i created a world it was extremely laggy and the log said this:

Farseek loaded a new chunk (-7, 24  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:30:50	FML	Farseek loaded a new chunk (-7, 27  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:30:52	FML	Farseek loaded a new chunk (-2, 30  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:30:59	FML	Farseek loaded a new chunk (-4, 31  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:04	FML	Farseek loaded a new chunk (-10, 29  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:07	FML	Farseek loaded a new chunk (-9, 14  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:08	FML	Farseek loaded a new chunk (-9, 11  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:09	FML	Farseek loaded a new chunk (-7, 9  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:10	FML	Farseek loaded a new chunk (6, 28  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:15	FML	Farseek loaded a new chunk (-13, 21  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:19	FML	Farseek loaded a new chunk (-12, 31  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:21	FML	Farseek loaded a new chunk (-16, 27  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:23	FML	Farseek loaded a new chunk (-16, 18  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:24	FML	Farseek loaded a new chunk (-13, 17  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:24	FML	Farseek loaded a new chunk (-15, 16  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:25	FML	Farseek loaded a new chunk (-17, 18  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:25	FML	Farseek loaded a new chunk (-13, 13  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
21:31:26	FML	Farseek loaded a new chunk (-13, 16  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by delvr** [comment]
Thanks for reporting! Please follow https://github.com/delvr/Farseek/issues/26 for updates.
