### ISSUE TITLE
Crash w/ BOP Mod

### ISSUE THREAD

**Issue by WenXin20** [delvr/Farseek#31]
Forge 2316-1.10.2
BOP v5.0.0.2236
Farseek v2.1
I get this crash when I load the game with Biomes O' Plenty. It doesn't crash without Farseek installed and Farseek doesn't crash without BOP.
[Crash Log](https://pastebin.com/hRN95U0t)

**Comment by JonoColwell** [comment]
Related to #27 ?

**Comment by delvr** [comment]
Hi WenXin20, I'm unable to reproduce this crash even after adding all the mods from your logs I could find. The only ones I'm missing is GuideBook 1.7 which seems unavailable for 1.10.2, and of course your personal mod wenxin2smisc. Do you get the same crash even when using only Forge, Farseek and BOP? If not, try gradually adding your other mods until the crash happens and let me know which one triggers it. Thanks!

**Comment by WenXin20** [comment]
Sorry it took so long to reply. I reupdated farseek to v2.1, but I am no longer receiving the crash after removing leather works mod. The mod was also causing a ModelBakery crash. I've reported it [here](https://minecraft.curseforge.com/projects/leather-works/issues/7), but no reply yet. If its unrelated to farseek, then this issue can probably be closed

**Comment by delvr** [comment]
That's good to hear! Thanks for the update. Let me know if this occurs again.
