### ISSUE TITLE
[Suggestion] Config option to remove the warning

### ISSUE THREAD

**Issue by Eufranio** [delvr/Farseek#32]
When the server is starting, for EACH world loaded, the game will print this:
```
[FML]: The following Farseek mod(s) can cause issues with existing worlds:
Streams: Can cause unexpected behavior such as incomplete rivers.
It is recommended to make backups of your world before proceeding.
Continue?
Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```
This is quite annoying when I know what I'm doing, I suggest you adding a config option to disable this message.

**Comment by JonoColwell** [comment]
per last comment on #16 there is apparently a patch prepared which will fix the check problem alongside fixing sponge capability.

**Comment by delvr** [comment]
This is correct, the underlying problem will soon go away without need for a config workaround. Merging this issue with https://github.com/delvr/Farseek/issues/16.
