### ISSUE TITLE
Farseek Causes Crash with current forge versions. (.2533-.2538) for 1.12.2

### ISSUE THREAD

**Issue by mysteryblock** [delvr/Farseek#34]
"java.lang.ArrayIndexOutOfBoundsException"

Given this, streams and repose also will not work.

**Comment by delvr** [comment]
I just generated a world with Forge 2536 and the latest Farseek, Streams and Repose and got no crash. Could you post your game log including the exception stack trace and the list of mods used? Thanks.

**Comment by mysteryblock** [comment]
Sure, I'll re-add farseek, streams, and repose, and get that.

**Comment by mysteryblock** [comment]
Farseek + streams + repose. Last Log. 
https://gist.github.com/mysteryblock/6188afafbd5a0048c79bdbf3c24e96d8

**Comment by mysteryblock** [comment]
Modlist: https://docs.google.com/spreadsheets/d/1W3KfRUMoKm8gSjmmEe_Y9TgXEpYvVWhhMqqp6xIOlME/edit?usp=sharing

**Comment by mysteryblock** [comment]
A proper crash-report did not generate, so I believe that's all I can send.

**Comment by mysteryblock** [comment]
I took out repose and left streams + farseek. I was able to load it with a pre-generated world as well as a new world. Not sure why, but before this combination would not work and gave me the error the thread is named after. Now it works i suppose, just not with Repose.

**Comment by delvr** [comment]
Thanks for the update and sorry for the delay on my end - so it seems that Streams works with your mods now but not Repose? Could you post the error log when using Repose? Thanks!

**Comment by mysteryblock** [comment]
Here is the log: https://gist.github.com/mysteryblock/6799019b809b6dff932c9faefeed9d83

I've updated to the latest farseek version and forge .2555 and the issue is still present unfortunately. 

As you said, farseek + streams works fine, just not repose.

**Comment by HypnoPants** [comment]
I'm having a similar problem, except I can't run farseek+streams or farseek+repose, or all 3... all of them cause errors, and I just updated all 3

**Comment by HypnoPants** [comment]
tested without any other mods (other than optifine)

farseek+streams+repose just gives an endless 'loading world' screen

**Comment by delvr** [comment]
@mysteryblock I'm looking at the mods involved in your crash stacktrace - could you try again without the Minestrapp and JustEnoughItems mods?
@HypnoPants I haven't been able to reproduce the freeze, using the latest versions of Forge, Farseek, Repose and OptiFine. Could you please attach your log file? Thanks.

**Comment by HypnoPants** [comment]
I hope this is the right log... [crash-2017-12-18_09.24.13-server](https://gist.github.com/HypnoPants/5f86c946322897b727c05a563f857cb9#file-crash-2017-12-18_09-24-13-server-txt)

**Comment by delvr** [comment]
That's a strange error... the Farseek core-mod mechanism is looking for a file that was was removed in version 2.2.1, as if you were using the latest 2.2.2 mod but still had the old core-mod config (META-INF/farseek_cm.cfg) from 2.2. That's included inside the jar though, so it should be replaced along with everything else. Is there any chance you may have been patching the Farseek mod jar instead of replacing it?

**Comment by HypnoPants** [comment]
I just tried deleting the farseek mod and downloading a fresh one, same non-loading result.

**Comment by delvr** [comment]
Hm, that's odd. I'm out of ideas for the moment but I'll let you know if I can figure it out.

**Comment by HypnoPants** [comment]
Okay. I've always loved the streams in all my worlds, adds such a nice touch (though shaders apparently cant figure them out)

**Comment by delvr** [comment]
I'm taking another look at this one now - is it possible you have another Farseek jar file in your mods directory? The Farseek coremod mechanism looks for .jar files that contain META-INF/farseek_cm.cfg. Normally duplicate mods would be detected and errored out by Forge but if you have something like a dev or sources jar in there it might cause trouble.

**Comment by HypnoPants** [comment]
Apparently that was the issue, I keep backups in separate folders within the mods folder... repose is even working too!

however... I'm scanning a new world, and I can't seem to find any farseek streams, just regular ones (with no current) but at least I'm not getting a never-ending loading screen :P

**Comment by HypnoPants** [comment]
ah, actually I did find one, it just took a hell of a lot of travelling in creative before I found one.

So it works apparently :)

Speaking of which, I always wondered, why are shaders not able to render the water in farseek streams?

They can render flowing water, but not farseek streams water.

**Comment by delvr** [comment]
Good to hear it's working for you! I'll close this issue and try to add a check for this situation in a future version. As for the shaders, please check these instructions from the FAQ in the mod's forum post and let me know if it doesn't work for you:

Starting with Streams 0.4 for Minecraft 1.9.4 or more recent, a block.properties file is provided in the mod's .jar archive (which you can open like a .zip file). Just copy that file to your shaderpack's "shaders" directory and you should be good to go. Note that you'll need a reasonably recent version of both OptiFine and your shaderpack (the block.properties file will specify the minimum OF version, if any). Note also that not all shaders will properly display Streams river current even if they render the water itself. For example SEUS shaders version 10.1 will show currents but 11.0 will not. (This is not something Streams has any control over). Also note: if shaders stop working for Streams blocks after a restart, disable and re-enable your shaderpack to fix this.
