### ISSUE TITLE
1.12.2 hang on world gen with OTG

### ISSUE THREAD

**Issue by Zygus42** [delvr/Farseek#35]
Farseek-1.12-2.2.1
Streams-1.12-0.4.1
OpenTerrainGenerator-1.12.2 - v2
Biome_Bundle-1.12.2-v6
forge-1.12.2-14.23.1.2556-installer-win

These are the latest version of all of the above as of now and I removed all other mods.

Without Streams+Farseek the world generates fine.  With Streams+Farseek it hangs during generation and I have to crash out of it.  I've included the crash report and the log file.  Please let me know if you need anything else.

[2017-12-01-6.log](https://github.com/delvr/Farseek/files/1519154/2017-12-01-6.log)
[crash-2017-12-01_03.01.00-server.txt](https://github.com/delvr/Farseek/files/1519155/crash-2017-12-01_03.01.00-server.txt)

**Comment by delvr** [comment]
Should be fixed in Farseek 1.12-2.2.2; please let me know if this still happens for you.

**Comment by Zygus42** [comment]
This is no longer crashing on world gen, but I also can't find any streams in the world.  I overflew a LOT of world in creative mode and never found a stream.  Is there any way to increase the spawn chance of streams ?

**Comment by Zygus42** [comment]
Update: I did eventually find a stream, so it is working, but the chance appears to be vanishingly small.
