### ISSUE TITLE
Unknown Property

### ISSUE THREAD

**Issue by Derjyn** [delvr/Farseek#36]
Could not get unknown property 'githubUser' for root project 'Farseek-1.12-2.2.3' of type org.gradle.api.Project

**Comment by delvr** [comment]
Hi Derjyn, thanks for reporting this. The build process was requiring `githubUser` to be defined somewhere (typically in the user's `gradle.properties` along with GitHub API keys and such), but I changed that in the new Farseek 2.2.4 release to use the new property `modAuthors` (typically from the project-level `gradle.properties`) instead. Please let me know if there's any issues with this new property. Thanks!
