### ISSUE TITLE
Client Crash - java.lang.ClassCastException: net.minecraft.util.math.ChunkPos cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by ProsperCraft** [delvr/Farseek#37]
https://gist.github.com/ProsperCraft/995db1b2c8deb8cb3e5eb31d272dd7b4

I created a new world, started running around, and then crashed.

**Comment by delvr** [comment]
This is caused by an internal change in Forge 1.12.2-14.23.2.2652. I will release a fix in the next few days, meanwhile please use Forge 1.12.2-14.23.2.2651 or earlier. Thanks!

**Comment by Darkosto** [comment]
Glad I happened to see this! I'll wait on my SevTech update until this one is ready. Thanks for looking at this!

**Comment by delvr** [comment]
Fixed in Farseek 2.2.5.
