### ISSUE TITLE
Crash with Crystals Mod

### ISSUE THREAD

**Issue by WenXin20** [delvr/Farseek#39]
Forge v14.23.3.2668-1.12.2
Crystals v1.0.1
Farseek v2.2.5
I got this crash upon creating a new world.
[Crash Log](https://pastebin.com/x4CFMpWQ)

**Comment by Sunconure11** [comment]
https://github.com/amadornes/ModJam5/issues/3

**Comment by delvr** [comment]
Linked issue is now resolved.
