### ISSUE TITLE
[1.12.2] Minecraft not launching with Farseek installed?

### ISSUE THREAD

**Issue by KoertLichtendonk** [delvr/Farseek#42]
Hey there, after adding Farseek for some reason Minecraft won't start, no crash report is being produced but it does throw out a few errors in the log. I tried installing different versions of the mod, if I install just the Streams mod it will just launch but say that I am missing Farseek. 

These are the versions I have.
Farseek 1.12 2.2.5
Streams 1.12 0.4.4

> [09:02:54] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class $wrapper.team.chisel.ctm.client.asm.CTMTransformer
> java.lang.ClassNotFoundException: $wrapper.team.chisel.ctm.client.asm.CTMTransformer
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129) [forge-1.12.2-14.23.4.2705-universal.jar:?]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer farseek.core.FarseekClassTransformer@163e8949 from coremod FarseekCoreMod
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 14 more
> Caused by: java.util.zip.ZipException: zip file is empty
> 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at farseek.core.FarseekClassTransformer.farseek$core$FarseekClassTransformer$$methodReplacements(FarseekCoreMod.scala:65) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer$$anonfun$1.apply(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer$$anonfun$1.apply(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186) ~[scala-library-2.11.1.jar:?]
> 	at farseek.core.FarseekClassTransformer.replacements$lzycompute(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer.replacements(FarseekCoreMod.scala:53) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer.transform(FarseekCoreMod.scala:87) ~[Farseek-1.12-2.2.5.jar:?]
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 14 more
> [09:02:54] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
> [09:02:54] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
> [09:02:54] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
> [09:02:54] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
> [09:02:54] [main/ERROR] [LaunchWrapper]: Unable to launch
> java.lang.ClassNotFoundException: net.minecraft.client.main.Main
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
> 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_171]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer farseek.core.FarseekClassTransformer@163e8949 from coremod FarseekCoreMod
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 14 more
> Caused by: java.util.zip.ZipException: zip file is empty
> 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_171]
> 	at farseek.core.FarseekClassTransformer.farseek$core$FarseekClassTransformer$$methodReplacements(FarseekCoreMod.scala:65) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer$$anonfun$1.apply(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer$$anonfun$1.apply(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) ~[scala-library-2.11.1.jar:?]
> 	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186) ~[scala-library-2.11.1.jar:?]
> 	at farseek.core.FarseekClassTransformer.replacements$lzycompute(FarseekCoreMod.scala:55) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer.replacements(FarseekCoreMod.scala:53) ~[Farseek-1.12-2.2.5.jar:?]
> 	at farseek.core.FarseekClassTransformer.transform(FarseekCoreMod.scala:87) ~[Farseek-1.12-2.2.5.jar:?]
> 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
> 	... 14 more
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [09:02:54] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
> [09:02:54] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
> [09:02:54] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
> Exception in thread "main" 
> Process exited with code 1.

**Comment by delvr** [comment]
Fixed in Farseek 2.3.1 - please let me know if you encounter other issues.
