### ISSUE TITLE
ServerHang when BOP and Farseek compete

### ISSUE THREAD

**Issue by kreezxil** [delvr/Farseek#44]
Happening during generation, not all the time but occasionally.

Dedicated Server Crash Log.

http://paste.ubuntu.com/p/GsXPNB2f48/

**Comment by delvr** [comment]
The recently-released Streams 0.4.8 should fix these timeouts in most cases, please give it a try and let me know if it still happens for you. Thanks!

**Comment by kreezxil** [comment]
holy smokes batman! I mean @delvr you really necro'd your own issue here.

I still run streams and I've been updating ever since I made that report, people have complained less and less over the time.

I'm just going to close this as there is really no way that I can test it.
