### ISSUE TITLE
Crash server 1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [delvr/Farseek#51]
[crash-2019-09-08_00.19.55-server.txt](https://github.com/delvr/Farseek/files/3587054/crash-2019-09-08_00.19.55-server.txt)

**Comment by Vagor96** [comment]
Looks like delvr/Streams#74

**Comment by delvr** [comment]
Thanks Vagor96, please see my comments on delvr/Streams#74 regarding the latest update.

**Comment by delvr** [comment]
The recently-released Streams 0.4.8 should fix these timeouts in most cases, please give it a try and let me know if it still happens for you. Thanks!
